weights: yolov5s.pt
cfg: /content/drive/My Drive/Deep_Learning/yolov5/models/yolov5s.yaml
data: /content/drive/My Drive/Deep_Learning/yolov5/data/Weapons.yaml
hyp: /content/drive/My Drive/Deep_Learning/yolov5/data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 24
project: runs/train
name: yolo_weapons_det
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolo_weapons_det5
